# Generated by Django 3.0.5 on 2020-05-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realters', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lising',
            new_name='Listing',
        ),
    ]
