# Generated by Django 3.0.5 on 2020-05-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200508_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='debrooms',
            new_name='bedrooms',
        ),
    ]
